### ISSUE TITLE
Unable to send messages from IoTedge hub to Azure IoTHub with proxy

### ISSUE THREAD

**Issue by keshav1git** [Azure/iotedge#1324]
## Expected Behavior
Messages from EdgeHub should be sent IoThub with confirmation in an environment which uses HTTP proxy

## Current Behavior
Not able to send messages to Azure IoTHub from EdgeHub. But on checking the `edgeHub` logs,  
I get error stating 

```only the "http" scheme is allowed for proxies```

![image](https://user-images.githubusercontent.com/25166512/59265249-98d09180-8c62-11e9-9e42-565ee80d03ea.png)
![image (2)](https://user-images.githubusercontent.com/25166512/59265278-ab4acb00-8c62-11e9-82c9-41380094e970.png)

## Context (Environment)
I'm trying to send messages to Azure IoTHub from Edge Hub. Being behind HTTP proxy, I have set proxy settings in config.yaml and in device twin.

Configs include
- http_proxy  
-UpstreamProtocol = ` AmqpWs`  

[Reference](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#feedback)

### Output of `iotedge check --output json`

![InkedInkedimage (9)_LI](https://user-images.githubusercontent.com/25166512/59266999-abe56080-8c66-11e9-86bc-1f75d3a18381.jpg)

### Device (Host) Operating System

Ubuntu 18.04 Bionic Server

### Container Operating System

Ubuntu-bionic version 

#### iotedged

IoT-edge version 1.0.7.1

![image (1)](https://user-images.githubusercontent.com/25166512/59265183-75a5e200-8c62-11e9-881f-3f0e243fd720.png)

#### Edge Agent

Edge Agent version 1.0.7.1
#### Edge Hub

Edge Hub version 1.0.7.1

#### Docker
docker version -18.09.06

## Additional Information
We were able to complete a WS through HTTP proxy test. We got the same result as documented in the [page](https://blogs.oracle.com/pavelbucek/websocket-via-http-proxy)

**Comment by arsing** [comment]
>Being behind HTTP proxy, I have set proxy settings in config.yaml and in device twin.

As the error indicates, you set a proxy URI that doesn't have the `http` scheme.

(Also note that the issue template asks you for the output of `iotedge check --output json`, whereas you've posted a screenshot instead of text, and the command in the screenshot was not run with `--output json`, and the screenshot is truncated.)

**Comment by keshav1git** [comment]
Hi,

 what does this statement mean :
"As the error indicates, you set a proxy URI that doesn't have the http scheme."

Can you explain me in brief and whats the solution? 

I encountered error when i ran `iotedge check --output json`
please find screenshot below:

<img width="329" alt="iotedge_error" src="https://user-images.githubusercontent.com/25166512/59407726-d56dcb80-8dcf-11e9-8ee8-e5632a5c5a1d.PNG">


please find config.yaml : 
![Inked_config-yaml_LI](https://user-images.githubusercontent.com/25166512/59422045-54bdc800-8ded-11e9-83be-c494952c8677.jpg)



please find edge-hub configs provided in device.twin.json:

![edge-hub-env_LI](https://user-images.githubusercontent.com/25166512/59422123-761eb400-8ded-11e9-999b-1f36d8e29465.jpg)

**Comment by candersonio** [comment]
> "As the error indicates, you set a proxy URI that doesn't have the http scheme."
Can you explain me in brief and whats the solution?

Means that you have a proxy that is not in the format "**http**://<proxy_url>:<proxy_port>".

Looking at the screenshot of your device twin json, you have "**https**://<proxy_url>:<proxy_port>". This is the cause of your error, try it with http instead. Here is how my proxy looks:
`"https_proxy": {
	"value": "http://<proxy_url>:8080"
},`

Looks like the documentation "[Configure an IoT Edge device to communicate through a proxy server](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#configure-the-iot-edge-agent)" is showing it using https as well. I think that is incorrect and should be updated to show http in all proxy uris.

Btw, using http here instead of https does **not** mean it won't allow https connections to be proxied.

**Comment by arsing** [comment]
@keshav1git

>I encountered error when i ran `iotedge check --output json`

Huh, I didn't realize `--output` wasn't in 1.0.7. I'll fix the issue template.

But still, please post text as text in the future, not a screenshot (and especially not a screenshot that truncates much of the useful information away).


>Can you explain me in brief and whats the solution?

What candersonio said is correct.

---

@candersonio

>Looks like the documentation "[Configure an IoT Edge device to communicate through a proxy server](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#configure-the-iot-edge-agent)" is showing it using https as well.

The one in the section you linked is `http`, but I do see one `https` in the [JSON deployment manifest files](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#json-deployment-manifest-files) section. I'll file a bug.

**Comment by arsing** [comment]
The docs have been fixed.

**Comment by keshav1git** [comment]
I'm still unable to send messages

Refer logs of edgehub:

<img width="326" alt="reauth_error" src="https://user-images.githubusercontent.com/25166512/59700345-c5f7e380-9210-11e9-9405-15399bf2fbee.PNG">
