### ISSUE TITLE
No such file or directory: '/iotedge/storage/'

### ISSUE THREAD

**Issue by ramkandimalla94** [Azure/iotedge#3596]
Hi Team,

We are facing challenges as a part of the development process for deploying Computer Vision models in the form of Python custom modules on Azure IoT Edge. We are using Azure VM with Linux.

I want to access a file from my **/iotedge/storage** which will be bound to the host machine

I followed the instructions as directed in [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module )

![image](https://user-images.githubusercontent.com/37137053/94057527-5e5e1a00-fdfd-11ea-9049-3d7848cfcac9.png)

I tried directly printing the directory with os.listdir('/iotedge/storage') which says no directory found.

![image](https://user-images.githubusercontent.com/37137053/94059508-26a4a180-fe00-11ea-8bfc-f23f95468f37.png)

**Can you help me in accessing the bound folder from my python custom module?**

this is my deployment.json snippet

![image](https://user-images.githubusercontent.com/37137053/94060089-fd384580-fe00-11ea-9f8e-ed382e90cdd9.png)

@vermaaditya FYI

**Comment by richma-ms** [comment]
Can you do a docker inspect on the container and provide the output?  In particular, I'm looking for whether the binds actually took  effect on the container.

**Comment by ramkandimalla94** [comment]
Output of docker inspect

[
    {
        "Id": "f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827",
        "Created": "2020-09-23T07:04:45.422991284Z",
        "Path": "python3",
        "Args": [
            "-u",
            "./main.py"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2566,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-09-24T04:10:56.455078Z",
            "FinishedAt": "2020-09-23T08:51:51.899285608Z"
        },
        "Image": "sha256:4770e34e0b6e460078ffb7f603cfe0e25d9aed46feec94a0c7f8e9423c5fa992",
        "ResolvConfPath": "/var/lib/docker/containers/f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827/hostname",
        "HostsPath": "/var/lib/docker/containers/f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827/hosts",
        "LogPath": "/var/lib/docker/containers/f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827/f3031ea239922badd587eaff9a762f2436fe176c59f9c446276dc6506e281827-json.log",
        "Name": "/SampleModule_prac_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                **"/var/run/iotedge/workload.sock:/var/run/iotedge/workload.sock"**
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/032f482edd4ba8a62784023ec47a84104f69d598c2f89104e09693013ac6863f-init/diff:/var/lib/docker/overlay2/a26b4a0e7e665c4bd5385cbb6618ed99cca8713bd34fe058c905888e5e3a3c33/diff:/var/lib/docker/overlay2/de5a35ed18245247e94c6cfc31e271776f7b510d61500bbe06eceb86e3ad1c2f/diff:/var/lib/docker/overlay2/81128365542bc6537dc68ba510f216a05b4bc6f96ad880a3e09779588e42a451/diff:/var/lib/docker/overlay2/06c6391f0f3796d52ca8f408c09392012109e2ab9851c09eb769c748f638cf85/diff:/var/lib/docker/overlay2/af424de918de823466b5bcff89195d2a2d98502f1d2c083aaf129c0af9dd3045/diff:/var/lib/docker/overlay2/f1602856f51ff574207557aa6504430fc9022cf6834f121d53c54c6e13bbd613/diff:/var/lib/docker/overlay2/9147e23d427c38d74135490915839223c1eeacab3e6bc0075809a50e41eec878/diff:/var/lib/docker/overlay2/55c0da25e88d56b4d9221d487b7a540bc471498ad396ae8a399d8d19de827f33/diff:/var/lib/docker/overlay2/6de2f6ce0bbb3663d3e587ba653e29832d10c58978c561125c8b198ce2ddb188/diff",
                "MergedDir": "/var/lib/docker/overlay2/032f482edd4ba8a62784023ec47a84104f69d598c2f89104e09693013ac6863f/merged",
                "UpperDir": "/var/lib/docker/overlay2/032f482edd4ba8a62784023ec47a84104f69d598c2f89104e09693013ac6863f/diff",
                "WorkDir": "/var/lib/docker/overlay2/032f482edd4ba8a62784023ec47a84104f69d598c2f89104e09693013ac6863f/work"
            },
            "Name": "overlay2"
        },
        **"Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/iotedge/workload.sock",
                "Destination": "/var/run/iotedge/workload.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],**
        "Config": {
            "Hostname": "f3031ea23992",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "IOTEDGE_APIVERSION=2019-01-30",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_MODULEGENERATIONID=637359539697712519",
                "IOTEDGE_MODULEID=SampleModule_prac_1",
                "IOTEDGE_DEVICEID=RamEdgeDevice",
                "IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock",
                "IOTEDGE_GATEWAYHOSTNAME=edgevmram",
                "RuntimeLogLevel=Information",
                "IOTEDGE_IOTHUBHOSTNAME=TestKepHub.azure-devices.net",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.8",
                "PYTHON_PIP_VERSION=20.2.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5578af97f8b2b466f4cdbebe18a3ba2d48ad1434/get-pip.py",
                "PYTHON_GET_PIP_SHA256=d4d62a0850fe0c2e6325b2cc20d818c580563de5a2038f917e3cb0e25280b4d1"
            ],
            "Cmd": [
                "python3",
                "-u",
                "./main.py"
            ],
            "Image": "XXXXXXXXXXX.azurecr.io/samplemodule_prac_1:0.0.1-amd64-7",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "070a981709abe9fdf38520550e6e4f78106538bdc503ee54226f99d00a384d84",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/070a981709ab",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "azure-iot-edge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "f3031ea23992"
                    ],
                   <info regarding network ID's address mentioned here>
                }
            }
        }
    }
]

**Comment by richma-ms** [comment]
Thanks.  There's a currently known issue where EdgeAgent won't update itself unless the image has changed.  So unfortunately just updating the bindings won't trigger a change in the container settings.

This has been fixed in 1.0.10-rc2, so give that a try if your situation allows.  Otherwise the workaround is to put the binds directly in the EdgeAgent section of the config.yaml so that it takes effect.

**Comment by ramkandimalla94** [comment]
HI, @richma-ms I am still facing the same issue.


This is what I mentioned in deployment file "Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"]
I am using Linux VM ... 

I tried with 1.0.10-rc2.

![image](https://user-images.githubusercontent.com/37137053/94761350-6819eb80-03c2-11eb-90b6-97fcdd5672e7.png)

in my python module i am tying to print os.listdir('/iotedge/storage/') to check if i am able to list the files of /etc/iotedge/storage/ assumuning it is now binded to /iotedge/storage/

but still the same "No such file error"

**Comment by veyalla** [comment]
You need to add the binds to the createOptions of the python module not the edgeHub or edgeAgent module. Can you clarify where you are adding them?

**Comment by ramkandimalla94** [comment]
@veyalla Thanks issue resolved
