### ISSUE TITLE
iotedge check error: config.yaml has correct URIs for daemon mgmt endpoint - Error

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge#3829]
## Expected Behavior
iotedge check should be passed

## Current Behavior
config.yaml has correct URIs for daemon mgmt endpoint - Error
  

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.updating iotedge daemon to 1.0.10
2.restart device
3.run iotedge check
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.10' locally
    1.0.10: Pulling from azureiotedge-diagnostics
    b9e6fec25718: Already exists
    909c0cde5070: Already exists
    c96327c6c17f: Already exists
    bbd8c93a942a: Already exists
    9b87e22bb11a: Already exists
    4d7335a78b54: Already exists
    df7387814126: Pulling fs layer
    c9f46c2fce6c: Pulling fs layer
    076984b59710: Pulling fs layer
    8368ffadb3f2: Pulling fs layer
    076984b59710: Waiting
    8368ffadb3f2: Waiting
    c9f46c2fce6c: Verifying Checksum
    c9f46c2fce6c: Download complete
    df7387814126: Verifying Checksum
    df7387814126: Download complete
    df7387814126: Pull complete
    8368ffadb3f2: Verifying Checksum
    8368ffadb3f2: Download complete
    c9f46c2fce6c: Pull complete
    076984b59710: Verifying Checksum
    076984b59710: Download complete
    076984b59710: Pull complete
    8368ffadb3f2: Pull complete
    Digest: sha256:01d3348865716a28ef84b0ddc2f69e7560d3a6d5425db3740960222f96e381d6
    Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-diagnostics:1.0.10
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows LTSB 2019
* Architecture [e.g. amd64, arm32, arm64]: arm64
* Container OS [e.g. Linux containers, Windows containers]:  Windows containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.10
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.10
* Docker/Moby [run `docker version`]: 1.40

**Comment by veyalla** [comment]
Thanks for the report, this is a known issue. A fix will be available in the coming week in a 1.0.10 patch.

**Comment by nainesh72** [comment]
Hi 
I have same issu on my win10 vm chen i go for iotedge-check it show me
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK

**Comment by nainesh72** [comment]
> A fix will be available in the coming weeks in a 1.0.10 patch

Hi 
i use 1.0.10 version but same issue

C:\WINDOWS\system32>iotedge version
iotedge 1.0.10 (c6350db898b2bd7abe1d50a340a1b1a91e72127d)

C:\WINDOWS\system32>iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
√ latest security daemon - OK

**Comment by spranav72** [comment]
It seems I have the same issue in Version # 1.0.10

× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)

Is there a fix or any  workaround?

**Comment by ebertrams** [comment]
HI @spranav72, Could you please try out the latest 1.0.10.1 release? Here it is: https://github.com/Azure/azure-iotedge/releases/tag/1.0.10.1 
It should fix this issue. Please confirm. Thanks.

**Comment by spranav72** [comment]
I uninstalled iotedge and then reinstalled latest 1.0.10.1 by specifying version number. It seems to work 👍

**Comment by ebertrams** [comment]
Great, thanks for the confirmation!

**Comment by nainesh72** [comment]
Thanks it work

Thanks
Nainesh
346-901-0770

________________________________

**Comment by nainesh72** [comment]
> HI @spranav72, Could you please try out the latest 1.0.10.1 release? Here it is: https://github.com/Azure/azure-iotedge/releases/tag/1.0.10.1
> It should fix this issue. Please confirm. Thanks.

Thanks Now it Work

**Comment by weijie-neo** [comment]
Hi, i am experiencing the issue even though I have updated to 1.0.10.1

× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Address not available var/run/iotedge/mgmt.sock)

$ apt list -a iotedge
Listing... Done
iotedge/bionic,now 1.0.10.1-1 amd64 [installed]

Am using Ubuntu 18.04 on Windows OS, followed the installation guide.

**Comment by veyalla** [comment]
@weijie-neo The issue you reported in fixed in 1.0.10.2 that was released a few days ago.

**Comment by damonbarry** [comment]
Fixed by #3950

**Comment by weijie-neo** [comment]
@veyalla Unfortunately I am still experiencing the same issue even after downloading the update.

× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
    caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)

**Comment by post2vishwa** [comment]
> @weijie-neo The issue you reported in fixed in 1.0.10.2 that was released a few days ago.

Hi Venkat,

I am trying to install iotedge latest version 1.0.10.2  on Cent OS 8.2 Operating system and observing same error. could you suggest. Thanks

Details:--

![image](https://user-images.githubusercontent.com/50254283/101560526-5cc1de00-3978-11eb-920e-e05ca86006db.png)

**Comment by wmk1** [comment]
Hello, I would like to bump it - I have the same issue, and unfortunately update or reverse IoT Edge version hasn't resolved anything. May I count for some help from you people? 

### Device Information
* Host OS : Windows 10
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedge version: 1.0.10.1
* Edge Agent: 1.0 
* Edge Hub : empty 
* Docker/Moby [run `docker version`]: Docker version 19.03.14+azure, build fd3371eb7df1adeceff5935cf3ade0576a0f48d5

## Logs

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.10.1' locally
    1.0.10.1: Pulling from azureiotedge-diagnostics
    20e126218ac6: Pulling fs layer
    3d156c2b3148: Pulling fs layer
    93c1a0dbe216: Pulling fs layer
    9a42988834d6: Pulling fs layer
    7edb483ee00a: Pulling fs layer
    c2accf0b2207: Pulling fs layer
    697f54ec860b: Pulling fs layer
    467f432763f3: Pulling fs layer
    5e865fb5ed6c: Pulling fs layer
    7edb483ee00a: Waiting
    c2accf0b2207: Waiting
    697f54ec860b: Waiting
    467f432763f3: Waiting
    5e865fb5ed6c: Waiting
    9a42988834d6: Waiting
    docker: error pulling image configuration: Get https://westeurope.data.mcr.microsoft.com/42012bb2682a4d76ba7fa17a9d9a9162-qb2vm9uiex//docker/registry/v2/blobs/sha256/fd/fdcf2190e6fcfae298934e1cfa39a35a3154eba178b297956849bcd18cfbc16e/data?P1=1609711717&P2=1&P3=1&P4=%2BwLkTDviToLtEzvBTGOP%2BMMyNdrnF9T8%2FrANz3iIPks%3D&se=2021-01-03T22%3A08%3A37Z&sig=Q6d1yon8oeehRAax6Y8r%2FqjQLirl1iT851KJFaroHFg%3D&sp=r&spr=https&sr=b&sv=2016-05-31&regid=42012bb2682a4d76ba7fa17a9d9a9162: dial tcp 204.79.197.219:443: i/o timeout.
    See 'docker run --help'.
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.10.1 but 1.0.10.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
× container time is close to host time - Error
    Could not query local time inside container
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-04-03 19:48:31 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the default network can connect to IoT Hub AMQP port - Error
    Container on the default network could not connect to qsns-euw-iot-hub-p.azure-devices.net:5671
× container on the default network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the default network could not connect to qsns-euw-iot-hub-p.azure-devices.net:443
× container on the default network can connect to IoT Hub MQTT port - Error
    Container on the default network could not connect to qsns-euw-iot-hub-p.azure-devices.net:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to qsns-euw-iot-hub-p.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to qsns-euw-iot-hub-p.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to qsns-euw-iot-hub-p.azure-devices.net:8883

10 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
9 check(s) raised errors. Re-run with --verbose for more details.

```

**Comment by damonbarry** [comment]
@wmk1 Based on this:

```
docker: error pulling image configuration: Get https://westeurope.data.mcr.microsoft.com/...: dial tcp 204.79.197.219:443: i/o timeout.
```
....it looks like docker encountered a temporary network condition. If you try again after some time it should succeed.

Also, can you try using the latest version 1.0.10.4 (rather than 1.0.10.1)? There was an additional fix in 1.0.10.2 that you might need.

**Comment by wmk1** [comment]
Hi damonbarry,

I have reverted version from 1.0.10-rc 1 to 1.0.10.1 but no success. I have try to install 1.0.10.4 and let you know as soon as possible.

**Comment by wmk1** [comment]
Hi damonbarry,

I have updated iotedge version to 1.0.10.4 as you proposed but same result :( furthermore, I cannot perform a build and push iot edge solution due to following error:

```
Sending build context to Docker daemon  438.8kB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
3.1-buster-arm32v7: Pulling from dotnet/core/sdk
709549ab8c59: Waiting
a47835026e1d: Waiting
d9aa96a1a673: Waiting
c4e19bdda1d2: Waiting
cae897984fff: Waiting
a882b67c741d: Waiting
b5e6c44c4652: Waiting
error pulling image configuration: Get https://westeurope.data.mcr.microsoft.com/42012bb2682a4d76ba7fa17a9d9a9162-qb2vm9uiex//docker/registry/v2/blobs/sha256/21/218f864f2706c61ddfb98e9a31ccb9ba121ea77891316e4a7797c0f3c7fafe47/data?P1=1609783748&P2=1&P3=1&P4=JYNoPXgK1iLBvONwwdWKubBFRqbQNITbCuIF1HHzDr0%3D&se=2021-01-04T18%3A09%3A08Z&sig=5qOlKnO1Fk%2FjCFPB%2Fz%2FnMEthe3wzv%2ByIWxA9nrlmEME%3D&sp=r&spr=https&sr=b&sv=2016-05-31&regid=42012bb2682a4d76ba7fa17a9d9a9162: dial tcp 204.79.197.219:443: i/o timeout
```

**Comment by damonbarry** [comment]
@wmk1 It looks like your most recent output comes from running `docker build` rather than `iotedge check`, is that right?

Regarding `iotedged` output, it looks like the daemon asks docker to stop the `actionHandler` container, but that fails. Do you know why docker can't stop that container? Are you able to stop it manually from the docker command line?

**Comment by wmk1** [comment]
Yes. The first line of this Dockerfile:

`FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env`

Docker cannot stop actionHandler container because of following error:

Error response from daemon: cannot stop container: actionHandler: Cannot kill container 7be3ae46adc033e6aeb92c018d77ce9c5b57c7c2007b4d7a1e048594223e9df9: unknown error after kill: runc did not terminate sucessfully: container_linux.go:392: signaling init process caused "permission denied"

**Comment by damonbarry** [comment]
What happens if you try to `docker stop actionHandler` (or `docker kill actionHandler`) from the command line?

Both of these issues seem to be specific to the docker installation on your device, and not IoT Edge. You may get better support in the appropriate docker forums.

**Comment by wmk1** [comment]
When I tried to stop these container, I had error that I have permission denied.

Yes, you were right. I have resolved a solution using docker forum.

For those people who might encounter following error: The issue is regarding docker daemon issue. I have resolved it using solution described here:  https://forums.docker.com/t/can-not-stop-docker-container-permission-denied-error/41142/5

```
A solution: 
1. sudo aa-status
2. sudo systemctl disable apparmor.service --now
3. sudo service apparmor teardown
4. sudo aa-status

After these steps I restarted ```docker``` and ```iotedge``` daemons and restarted my RPI. After restarting I have everything working again. The issue happened when I tried to upgrade to newer version of IoT Edge and perhaps it was due to not fully removing some docker/iotedge stuff. Please be aware when performing such stuff. 
```

**Comment by GertjanvanhetHof** [comment]
I'm running in the same issue. I try to setup my IoT Edge with DPS and certificates.

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )


In the logs I found:

Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [INFO] - Starting service...
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [INFO] - Version - 1.2.4
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [INFO] - Provisioning starting. Reason: Startup
Jan 04 13:23:11 vm-iot-edge-dev aziot-certd[2616]: 2022-01-04T13:23:11Z [INFO] - <-- GET /certificates/device-id?api-version=2020-09-01 {"host": "certd.sock"}
Jan 04 13:23:11 vm-iot-edge-dev aziot-certd[2616]: 2022-01-04T13:23:11Z [INFO] - --> 200 {"content-type": "application/json"}
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [INFO] - <-- GET /keypair/device-id?api-version=2020-09-01 {"host": "keyd.sock"}
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [ERR!] - Permission denied (os error 13)
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [ERR!] - !!! internal error
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [ERR!] - !!! caused by: could not load key pair
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [ERR!] - !!! caused by: could not load key pair: AZIOT_KEYS_RC_ERR_EXTERNAL
Jan 04 13:23:11 vm-iot-edge-dev aziot-keyd[2621]: 2022-01-04T13:23:11Z [INFO] - --> 500 {"content-type": "application/json"}
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [ERR!] - service encountered an error
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [ERR!] - caused by: DPS client error
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [ERR!] - caused by: internal error
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]: 2022-01-04T13:23:11Z [ERR!] -    0: <unknown>
Jan 04 13:23:11 vm-iot-edge-dev aziot-identityd[11371]:    1: <unknown>
Jan 04 13:23:11 vm-iot-edge-dev systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:23:11 vm-iot-edge-dev systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
